### ISSUE TITLE
what is this error?

### ISSUE THREAD

**Issue by netcrave** [simonyiszk/openwebrx#107]
```
 ✘  erratic@shells  ~  docker run -p 8073:8073 \
--device=/dev/bus/usb:/dev/bus/usb \
-v /srv/openwebrx/config_webrx.py:/opt/openwebrx/config_webrx.py \
thomx/openwebrx
Ncat: Version 6.47 ( http://nmap.org/ncat )
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
Found 1 device(s):
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
Using device 0: Generic RTL2832U OEM
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "openwebrx.py", line 284, in spectrum_thread_function
    spectrum_dsp=dsp=getattr(plugins.dsp,cfg.dsp_plugin).plugin.dsp_plugin()
AttributeError: 'module' object has no attribute 'dsp_plugin'

Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Sampling at 2400000 S/s.
Tuned to 144250000 Hz.
Tuner gain set to 3.70 dB.
Reading samples in async mode...


```

specifically this 

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "openwebrx.py", line 284, in spectrum_thread_function
    spectrum_dsp=dsp=getattr(plugins.dsp,cfg.dsp_plugin).plugin.dsp_plugin()
AttributeError: 'module' object has no attribute 'dsp_plugin'
```

**Comment by ha7ilm** [comment]
I don't know, I have not yet ran OpenWebRX on `docker`. Are you using `python2` (not `python3` for sure)?  Are you using the latest version of OpenWebRX? If you test `rtl_sdr` on its own, like `rtl_sdr - | csdr through > /dev/null`, does it work?
