### ISSUE TITLE
Issues with installation of openwebrx on Raspberry Pi 3

### ISSUE THREAD

**Issue by spectrumcomputing** [simonyiszk/openwebrx#143]
Hello,

I have a rtl-sdr blog v3 SDR Stick, and have installed openwebrx on a clean install of Raspbian Buster on my Raspberry Pi3.  I followed these instructions and it seems to go without error.

https://blog.sdr.hu/2015/06/30/quick-setup-openwebrx.html

I have tested that I can hear radio by running this command:

`rtl_fm -M wbfm -f 98.8M | play -r 32k -t raw -e s -b 16 -c 1 -V1 -`

My problem is that I don't seem to have all the normal controls available when I launch the webpage that I normally see on the other examples of openwebrx I have seen:

![image](https://user-images.githubusercontent.com/38283339/71531823-5b72df00-28e8-11ea-8888-5b69e14f59da.png)

I have changed centre frequency with:

`center_freq=106200000`

and rf gain with 

`rf_gain=0`

But I just hear noise and not the FM station I'm expecting. I understand that the range can only be around 2.4Mhz.  How do I change frequency within the web application?  I have looked at the following page, but can't see anything appropriate. 

https://github.com/simonyiszk/openwebrx/wiki

I have pasted what comes up on the command line here (This is before I changed the center_freq setting)

Thank you. 

Peter Jones

```
pi@raspberrypi:~/openwebrx $ ./openwebrx.py
 
 
OpenWebRX - Open Source SDR Web App for Everyone!  | for license see LICENSE file in the package
_________________________________________________________________________________________________
 
Author contact info:    Andras Retzler, HA7ILM <randras@sdr.hu>
 
[openwebrx-main] Configuration script not specified. I will use: "config_webrx.py"
[openwebrx-main] nmux_bufsize = 602112, nmux_bufcnt = 84
[openwebrx-main] Started rtl_thread: rtl_sdr -D2 -s 2400000 -f 144250000 -p 0 -g 5 -| nmux --bufsize 602112 --bufcnt 84 --port 4951 --address 127.0.0.1
[openwebrx-main] Waiting for I/Q server to start...
nmux: listening on 127.0.0.1:4951
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001
 
Using device 0: Generic RTL2832U OEM
[openwebrx-main] I/Q server started.
nmux: pthread_create() done, clients now: 1
[openwebrx-main] Starting watchdog threads.
client 0x144f680: started!
[openwebrx-main] Starting spectrum thread.
[openwebrx-spectrum] Spectrum thread initialized successfully.
[openwebrx-dsp-plugin:csdr] Command = nc -v 127.0.0.1 4951 | csdr convert_u8_f | csdr fft_cc 4096 2867 | csdr logaveragepower_cf -70 4096 93 | csdr fft_exchange_sides_ff 4096 | csdr compress_fft_adpcm_f_u8 4096
[openwebrx-spectrum] Spectrum thread started.
[openwebrx-main] Starting HTTP server.
nmux: pthread_create() done, clients now: 2
Connection to 127.0.0.1 4951 port [tcp/*] succeeded!
client 0x144f748: started!
Found Rafael Micro R820T tuner
Enabled direct sampling mode, input 2
Enabled direct sampling mode, input 2/Q.
Sampling at 2400000 S/s.
Tuned to 144250000 Hz.
Tuner gain set to 3.70 dB.
Reading samples in async mode...
client 0x144f680: CS_THREAD_FINISHED, client_goto_source = 2, errno = 32192.168.1.217 - - [27/Dec/2019 20:21:01] "GET / HTTP/1.1" 200 -
[openwebrx-httpd] client 192.168.1.217#308b1f468197bf1a57b79896bfc18a75 :: client added. Clients now: 1
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /sdr.js HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /jquery.nanoscroller.js HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /nanoscroller.css HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /jquery-3.2.1.min.js HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /openwebrx.js HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /mathbox-bundle.min.js HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /openwebrx.css HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /gfx/openwebrx-top-photo.jpg HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /gfx/openwebrx-top-logo.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /gfx/openwebrx-avatar-background.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /gfx/openwebrx-ha5kfu-top-logo.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /gfx/openwebrx-avatar.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /gfx/openwebrx-rx-details-arrow-up.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:01] "GET /gfx/openwebrx-rx-details-arrow.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-panel-status.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-panel-log.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-panel-receiver.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-speaker.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-waterfall-auto.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-squelch-button.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-waterfall-default.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-zoom-in.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-zoom-out.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:02] "GET /gfx/openwebrx-zoom-in-total.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:03] "GET /gfx/openwebrx-zoom-out-total.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:03] "GET /gfx/openwebrx-3d-spectrum.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:03] "GET /gfx/openwebrx-play-button.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:04] "GET /gfx/openwebrx-scale-background.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:04] "GET /gfx/openwebrx-background-cool-blue.png HTTP/1.1" 200 -
192.168.1.217 - - [27/Dec/2019 20:21:04] "GET /gfx/font-expletus-sans/ExpletusSans-Medium.ttf HTTP/1.1" 200 -
[openwebrx-ws] Client requested WebSocket connection
[openwebrx-httpd:ws,0] command: SET output_rate=12000 action=start
[openwebrx-dsp-plugin:csdr] Command = nc -v 127.0.0.1 4951 | csdr convert_u8_f | csdr shift_addition_cc --fifo /tmp/openwebrx_pipe_1968963136_shift_pipe | csdr fir_decimate_cc 199 0.00075375 HAMMING | csdr bandpass_fir_fft_cc --fifo /tmp/openwebrx_pipe_1968963136_bpf_pipe 0.0265339966833 HAMMING | csdr squelch_and_smeter_cc --fifo /tmp/openwebrx_pipe_1968963136_squelch_pipe --outfifo /tmp/openwebrx_pipe_1968963136_smeter_pipe 5 1 | csdr fmdemod_quadri_cf | csdr limit_ff | csdr old_fractional_decimator_ff 1.005 | csdr deemphasis_nfm_ff 11025 | csdr fastagc_ff 1024 | csdr convert_f_s16 | csdr encode_ima_adpcm_i16_u8
csdr old_fractional_decimator_ff: window = HAMMING
csdr old_fractional_decimator_ff: taps_length = 133
csdr shift_addition_cc: nmux: pthread_create() done, clients now: 2
fifo control mode on
client 0x144f830: started!
Connection to 127.0.0.1 4951 port [tcp/*] succeeded!
fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: padded_taps_length = 5312
csdr fir_decimate_cc: taps = a95168
csdr fir_decimate_cc: NEON aligned taps = a95180
csdr squelch_and_smeter_cc: csdr bandpass_fir_fft_cc: fifo control mode on
fifo control mode on
csdr shift_addition_cc: reinitialized to -0
csdr squelch_and_smeter_cc: initial squelch level is 0
csdr bandpass_fir_fft_cc: (fft_size = 512) = (taps_length = 151) + (input_size = 362) - 1
(overlap_length = 150) = taps_length - 1
csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.331675, high_cut = 0.331675
[openwebrx-httpd:ws,0] command: SET audio_rate=48000
[openwebrx-httpd:ws] invalid parameter
[openwebrx-httpd:ws,0] command: SET secondary_mod=off
[openwebrx-dsp-plugin:csdr] Command = nc -v 127.0.0.1 4951 | csdr convert_u8_f | csdr shift_addition_cc --fifo /tmp/openwebrx_pipe_1968963136_shift_pipe | csdr fir_decimate_cc 199 0.00075375 HAMMING | csdr bandpass_fir_fft_cc --fifo /tmp/openwebrx_pipe_1968963136_bpf_pipe 0.0265339966833 HAMMING | csdr squelch_and_smeter_cc --fifo /tmp/openwebrx_pipe_1968963136_squelch_pipe --outfifo /tmp/openwebrx_pipe_1968963136_smeter_pipe 5 1 | csdr fmdemod_quadri_cf | csdr limit_ff | csdr old_fractional_decimator_ff 1.005 | csdr deemphasis_nfm_ff 11025 | csdr fastagc_ff 1024 | csdr convert_f_s16 | csdr encode_ima_adpcm_i16_u8
client 0x144f830: CS_THREAD_FINISHED, client_goto_source = 2, errno = 104csdr shift_addition_cc: fifo control mode on
csdr old_fractional_decimator_ff: window = HAMMING
csdr bandpass_fir_fft_cc: fifo control mode on
csdr shift_addition_cc: reinitialized to -0
csdr old_fractional_decimator_ff: taps_length = 133
csdr bandpass_fir_fft_cc: (fft_size = 512) = (taps_length = 151) + (input_size = 362) - 1
(overlap_length = 150) = taps_length - 1
csdr squelch_and_smeter_cc: fir_decimate_cc: taps_length = 5307
fifo control mode on
csdr fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: padded_taps_length = 5312
csdr fir_decimate_cc: taps = 1ae7168
csdr fir_decimate_cc: NEON aligned taps = 1ae7180
csdr squelch_and_smeter_cc: initial squelch level is 0
[openwebrx-httpd:ws,0] command: SET mod=nfm low_cut=-4000 high_cut=4000 offset_freq=0
Connection to 127.0.0.1 4951 port [tcp/*] succeeded!
nmux: pthread_create() done, clients now: 2
client 0x144f860: started!
csdr shift_addition_cc: reinitialized to -0
csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.331675, high_cut = 0.331675
csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.331675, high_cut = 0.331675
[openwebrx-httpd:ws,0] command: SET secondary_mod=off
client 0x144f860: CS_THREAD_FINISHED, client_goto_source = 2, errno = 104[openwebrx-dsp-plugin:csdr] Command = nc -v 127.0.0.1 4951 | csdr convert_u8_f | csdr shift_addition_cc --fifo /tmp/openwebrx_pipe_1968963136_shift_pipe | csdr fir_decimate_cc 199 0.00075375 HAMMING | csdr bandpass_fir_fft_cc --fifo /tmp/openwebrx_pipe_1968963136_bpf_pipe 0.0265339966833 HAMMING | csdr squelch_and_smeter_cc --fifo /tmp/openwebrx_pipe_1968963136_squelch_pipe --outfifo /tmp/openwebrx_pipe_1968963136_smeter_pipe 5 1 | csdr fmdemod_quadri_cf | csdr limit_ff | csdr old_fractional_decimator_ff 1.005 | csdr deemphasis_nfm_ff 11025 | csdr fastagc_ff 1024 | csdr convert_f_s16 | csdr encode_ima_adpcm_i16_u8
nmux: pthread_create() done, clients now: 2
Connection to 127.0.0.1 4951 port [tcp/*] succeeded!
client 0x144f890: started!
csdr old_fractional_decimator_ff: window = HAMMING
csdr old_fractional_decimator_ff: taps_length = 133
csdr squelch_and_smeter_cc: fir_decimate_cc: taps_length = 5307
fifo control mode on
csdr fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: padded_taps_length = 5312
csdr fir_decimate_cc: taps = 1905168
csdr fir_decimate_cc: NEON aligned taps = 1905180
csdr bandpass_fir_fft_cc: fifo control mode on
csdr bandpass_fir_fft_cc: (fft_size = 512) = (taps_length = 151) + (input_size = 362) - 1
(overlap_length = 150) = taps_length - 1
csdr shift_addition_cc: fifo control mode on
csdr squelch_and_smeter_cc: initial squelch level is 0
csdr shift_addition_cc: reinitialized to -0
[openwebrx-httpd:ws,0] command: SET mod=nfm low_cut=-4000 high_cut=4000 offset_freq=0
csdr shift_addition_cc: reinitialized to -0
csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.331675, high_cut = 0.331675
csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.331675, high_cut = 0.331675
[openwebrx-httpd:ws,0] command: SET secondary_mod=off
client 0x144f890: CS_THREAD_FINISHED, client_goto_source = 2, errno = 104[openwebrx-dsp-plugin:csdr] Command = nc -v 127.0.0.1 4951 | csdr convert_u8_f | csdr shift_addition_cc --fifo /tmp/openwebrx_pipe_1968963136_shift_pipe | csdr fir_decimate_cc 199 0.00075375 HAMMING | csdr bandpass_fir_fft_cc --fifo /tmp/openwebrx_pipe_1968963136_bpf_pipe 0.0265339966833 HAMMING | csdr squelch_and_smeter_cc --fifo /tmp/openwebrx_pipe_1968963136_squelch_pipe --outfifo /tmp/openwebrx_pipe_1968963136_smeter_pipe 5 1 | csdr fmdemod_quadri_cf | csdr limit_ff | csdr old_fractional_decimator_ff 1.005 | csdr deemphasis_nfm_ff 11025 | csdr fastagc_ff 1024 | csdr convert_f_s16 | csdr encode_ima_adpcm_i16_u8
csdr shift_addition_cc: fifo control mode on
fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: padded_taps_length = 5312
csdr fir_decimate_cc: taps = 1666168
csdr fir_decimate_cc: NEON aligned taps = 1666180
csdr bandpass_fir_fft_cc: fifo control mode on
csdr shift_addition_cc: reinitialized to -0
csdr bandpass_fir_fft_cc: (fft_size = 512) = (taps_length = 151) + (input_size = 362) - 1
(overlap_length = 150) = taps_length - 1
csdr squelch_and_smeter_cc: fifo control mode on
nmux: pthread_create() done, clients now: 2
client 0x144f8c0: started!
Connection to 127.0.0.1 4951 port [tcp/*] succeeded!
csdr old_fractional_decimator_ff: window = HAMMING
csdr old_fractional_decimator_ff: taps_length = 133
csdr squelch_and_smeter_cc: initial squelch level is 0
[openwebrx-httpd:ws,0] command: SET mod=nfm low_cut=-4000 high_cut=4000 offset_freq=0
csdr shift_addition_cc: reinitialized to -0
csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.331675, high_cut = 0.331675
csdr bandpass_fir_fft_cc: filter initialized, low_cut = -0.331675, high_cut = 0.331675
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET / HTTP/1.1" 200 -
[openwebrx-httpd] client 192.168.1.234#f7416c4b486ffc427b125007b81c6ec5 :: client added. Clients now: 2
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /sdr.js HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /nanoscroller.css HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /openwebrx.css HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /openwebrx.js HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /jquery.nanoscroller.js HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /jquery-3.2.1.min.js HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /mathbox-bundle.min.js HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-top-photo.jpg HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-top-logo.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-ha5kfu-top-logo.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-avatar-background.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-avatar.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-rx-details-arrow-up.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-rx-details-arrow.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-panel-status.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-panel-log.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-panel-receiver.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-waterfall-auto.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-speaker.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-squelch-button.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-background-cool-blue.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:53] "GET /gfx/openwebrx-scale-background.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/font-expletus-sans/ExpletusSans-Medium.ttf HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/openwebrx-waterfall-default.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/openwebrx-zoom-in.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/openwebrx-zoom-out.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/openwebrx-zoom-in-total.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/openwebrx-zoom-out-total.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/openwebrx-play-button.png HTTP/1.1" 200 -
192.168.1.234 - - [27/Dec/2019 20:27:54] "GET /gfx/openwebrx-3d-spectrum.png HTTP/1.1" 200 -
[openwebrx-ws] Client requested WebSocket connection
[openwebrx-httpd:ws,1] command: SET output_rate=12000 action=start
[openwebrx-dsp-plugin:csdr] Command = nc -v 127.0.0.1 4951 | csdr convert_u8_f | csdr shift_addition_cc --fifo /tmp/openwebrx_pipe_1968963096_shift_pipe | csdr fir_decimate_cc 199 0.00075375 HAMMING | csdr bandpass_fir_fft_cc --fifo /tmp/openwebrx_pipe_1968963096_bpf_pipe 0.0265339966833 HAMMING | csdr squelch_and_smeter_cc --fifo /tmp/openwebrx_pipe_1968963096_squelch_pipe --outfifo /tmp/openwebrx_pipe_1968963096_smeter_pipe 5 1 | csdr fmdemod_quadri_cf | csdr limit_ff | csdr old_fractional_decimator_ff 1.005 | csdr deemphasis_nfm_ff 11025 | csdr fastagc_ff 1024 | csdr convert_f_s16 | csdr encode_ima_adpcm_i16_u8
csdr bandpass_fir_fft_cc: fifo control mode on
csdr shift_addition_cc: fifo control mode on
csdr old_fractional_decimator_ff: csdr bandpass_fir_fft_cc: (fft_size = 512) = (taps_length = 151) + (input_size = 362) - 1
(overlap_length = 150) = taps_length - 1
csdr shift_addition_cc: reinitialized to -0
nmux: pthread_create() done, clients now: 3
Connection to 127.0.0.1 4951 port [tcp/*] succeeded!
window = HAMMING
csdr old_fractional_decimator_ff: taps_length = 133
csdr squelch_and_smeter_cc: fifo control mode on
csdr squelch_and_smeter_cc: initial squelch level is 0
client 0x144f8f0: started!
fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: taps_length = 5307
csdr fir_decimate_cc: padded_taps_length = 5312
csdr fir_decimate_cc: taps = 1b4d168
csdr fir_decimate_cc: NEON aligned taps = 1b4d180
[openwebrx-httpd:ws] exception:  <class 'socket.error'> [Errno 32] Broken pipe
  File "./openwebrx.py", line 498, in do_GET
    rxws.send(self, spectrum_data[0],"FFT ")
  File "/home/pi/openwebrx/rxws.py", line 164, in send
    myself.wfile.write(header+data_to_send)
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
client 0x144f8c0: CS_THREAD_FINISHED, client_goto_source = 2, errno = 104[openwebrx-httpd] client 192.168.1.217#308b1f468197bf1a57b79896bfc18a75 :: client being closed.
[openwebrx-dsp-plugin:csdr] try_delete_pipes() :: [Errno 2] No such file or directory: '/tmp/openwebrx_pipe_1968963136_bpf_pipe'
[openwebrx-dsp-plugin:csdr] try_delete_pipes() :: [Errno 2] No such file or directory: '/tmp/openwebrx_pipe_1968963136_shift_pipe'
[openwebrx-dsp-plugin:csdr] try_delete_pipes() :: [Errno 2] No such file or directory: '/tmp/openwebrx_pipe_1968963136_squelch_pipe'
[openwebrx-dsp-plugin:csdr] try_delete_pipes() :: [Errno 2] No such file or directory: '/tmp/openwebrx_pipe_1968963136_smeter_pipe'
----------------------------------------
Exception happened during processing of request from ('192.168.1.217', 50492)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by ha7ilm** [comment]
> My problem is that I don't seem to have all the normal controls available when I launch the webpage that I normally see on the other examples of openwebrx I have seen:

You are seeing the correct interface with all the controls.  
WFM is not supported.
